window.STARTER_ITEMS = [
  {
    "id": "M01",
    "name": "タイトル・フェードアップ",
    "category": "モーション",
    "method": "AE",
    "desc": "章タイトルを下から自然に出す",
    "use": "会社紹介 / サービス紹介 / 章扉",
    "tech": "Position + Opacity / Easy Ease",
    "note": "移動は20〜40px程度。大きく動かしすぎない。",
    "tags": "タイトル 見出し フェード",
    "youtube": "https://www.youtube.com/results?search_query=After+Effects+title+fade+up+tutorial",
    "preview": "title",
    "animate": true
  },
  {
    "id": "M02",
    "name": "マスク・リビール",
    "category": "モーション",
    "method": "AE",
    "desc": "文字や画像を面の中から見せる",
    "use": "見出し / 製品名 / サービス名",
    "tech": "Track Matte / Mask / Position",
    "note": "出現方向を画面内で統一する。",
    "tags": "マスク リビール テキスト",
    "youtube": "https://www.youtube.com/results?search_query=After+Effects+mask+reveal+text+tutorial",
    "preview": "mask",
    "animate": true
  },
  {
    "id": "M03",
    "name": "キーワード強調",
    "category": "モーション",
    "method": "AE",
    "desc": "重要語だけサイズと色で強調する",
    "use": "メリット / 特徴 / 数値",
    "tech": "Scale / Color / Opacity",
    "note": "ビジネス動画では弾ませすぎない。",
    "tags": "強調 ポップ キーワード",
    "youtube": "https://www.youtube.com/results?search_query=After+Effects+text+pop+animation+tutorial",
    "preview": "keyword",
    "animate": false
  },
  {
    "id": "M04",
    "name": "アイコン・ポップイン",
    "category": "モーション",
    "method": "AE",
    "desc": "機能や特徴をアイコンで分かりやすく見せる",
    "use": "特徴3点 / 機能紹介",
    "tech": "Scale / Opacity / Stagger",
    "note": "3〜5フレームずつずらすと自然。",
    "tags": "アイコン 機能 特徴",
    "youtube": "https://www.youtube.com/results?search_query=After+Effects+icon+pop+animation+tutorial",
    "preview": "icons",
    "animate": true
  },
  {
    "id": "D01",
    "name": "カウントアップ",
    "category": "図解・データ",
    "method": "AE",
    "desc": "導入社数や実績値を大きく見せる",
    "use": "KPI / 導入実績 / 削減時間",
    "tech": "Slider Control / Source Text",
    "note": "最終値を0.5秒以上止める。",
    "tags": "数字 KPI カウント",
    "youtube": "https://www.youtube.com/watch?v=cXxuWBQQ4vY",
    "preview": "count",
    "animate": true
  },
  {
    "id": "D02",
    "name": "KPIカード",
    "category": "図解・データ",
    "method": "AE",
    "desc": "3つの主要指標をカードで整理する",
    "use": "成果 / 実績 / 月次レポート",
    "tech": "Grid / Position / Opacity",
    "note": "3項目程度に絞ると読みやすい。",
    "tags": "KPI カード 数字",
    "youtube": "https://www.youtube.com/results?search_query=After+Effects+KPI+card+animation",
    "preview": "kpi",
    "animate": false
  },
  {
    "id": "D03",
    "name": "棒グラフ",
    "category": "図解・データ",
    "method": "AE",
    "desc": "数値差を直感的に比較する",
    "use": "実績比較 / アンケート",
    "tech": "Shape Layer / Scale Y",
    "note": "0基準を崩さず、差を誇張しない。",
    "tags": "棒グラフ データ 比較",
    "youtube": "https://www.youtube.com/watch?v=BHtkYj8pW4Y",
    "preview": "bars",
    "animate": true
  },
  {
    "id": "D04",
    "name": "3ステップ・フロー",
    "category": "図解・データ",
    "method": "AE",
    "desc": "サービス利用の流れを順番に説明する",
    "use": "導入フロー / 利用手順",
    "tech": "Shape Layer / Trim Paths",
    "note": "1→2→3の順で視線を誘導する。",
    "tags": "フロー ステップ 手順",
    "youtube": "https://www.youtube.com/results?search_query=After+Effects+process+flow+animation",
    "preview": "flow",
    "animate": true
  },
  {
    "id": "D05",
    "name": "Before → After",
    "category": "図解・データ",
    "method": "AE",
    "desc": "導入前後の変化を一目で比較する",
    "use": "課題→解決 / 導入効果",
    "tech": "Layout / Position / Opacity",
    "note": "After側だけアクセント色を使う。",
    "tags": "Before After 改善 比較",
    "youtube": "https://www.youtube.com/results?search_query=After+Effects+before+after+animation",
    "preview": "beforeafter",
    "animate": false
  },
  {
    "id": "L01",
    "name": "左テキスト＋右ビジュアル",
    "category": "構図・レイアウト",
    "method": "AE",
    "desc": "説明と画を安定して見せる定番構図",
    "use": "サービス説明 / 会社紹介",
    "tech": "Grid / Safe Area / Position",
    "note": "5:5〜6:4、余白を広く取る。",
    "tags": "2カラム 左右 レイアウト",
    "youtube": "https://www.youtube.com/results?search_query=corporate+video+layout+motion+graphics",
    "preview": "split",
    "animate": false
  },
  {
    "id": "L02",
    "name": "人物＋ローワーサード",
    "category": "構図・レイアウト",
    "method": "撮影＋AE",
    "desc": "人物を主役にしながら氏名・役職を補足する",
    "use": "インタビュー / 社員紹介",
    "tech": "Lower Third / Safe Area",
    "note": "顔とテロップが競合しない位置に置く。",
    "tags": "人物 名前 役職 インタビュー",
    "youtube": "https://www.youtube.com/results?search_query=After+Effects+lower+third+corporate+tutorial",
    "preview": "lowerthird",
    "animate": true
  },
  {
    "id": "L03",
    "name": "UI＋解説パネル",
    "category": "構図・レイアウト",
    "method": "AE",
    "desc": "サービス画面と説明を同時に見せる",
    "use": "SaaS / Webサービス紹介",
    "tech": "Pre-compose / Scale / Position",
    "note": "画面キャプチャを小さくしすぎない。",
    "tags": "UI SaaS 解説 パネル",
    "youtube": "https://www.youtube.com/results?search_query=After+Effects+SaaS+UI+animation+tutorial",
    "preview": "uipanel",
    "animate": false
  },
  {
    "id": "C01",
    "name": "固定カメラ",
    "category": "カメラワーク",
    "method": "撮影",
    "desc": "内容に集中させる基本の撮り方",
    "use": "インタビュー / 社長メッセージ",
    "tech": "三脚 / 構図設計",
    "note": "背景の水平・垂直を整える。",
    "tags": "固定 インタビュー 三脚",
    "youtube": "https://www.youtube.com/watch?v=IiyBo-qLDeM",
    "preview": "staticcam",
    "animate": false
  },
  {
    "id": "C02",
    "name": "パン",
    "category": "カメラワーク",
    "method": "撮影",
    "desc": "左右に振ってオフィスや施設を紹介する",
    "use": "オフィス / 施設紹介",
    "tech": "三脚ヘッド / ジンバル",
    "note": "始点と終点を先に決める。",
    "tags": "パン 左右 オフィス",
    "youtube": "https://www.youtube.com/watch?v=IiyBo-qLDeM",
    "preview": "pan",
    "animate": true
  },
  {
    "id": "C03",
    "name": "プッシュイン",
    "category": "カメラワーク",
    "method": "撮影＋AE",
    "desc": "重要な人物・発言へゆっくり寄る",
    "use": "インタビュー / 製品紹介",
    "tech": "撮影移動 or Scale 100→108",
    "note": "4K素材をFHDで使うと疑似寄りでも画質を保ちやすい。",
    "tags": "プッシュイン 寄る 強調",
    "youtube": "https://www.youtube.com/watch?v=IiyBo-qLDeM",
    "preview": "pushin",
    "animate": true
  },
  {
    "id": "C04",
    "name": "ラックフォーカス",
    "category": "カメラワーク",
    "method": "撮影＋AE",
    "desc": "手前と奥の注目対象を切り替える",
    "use": "手元→画面 / 製品→人物",
    "tech": "フォーカス送り / Blurで模擬",
    "note": "意味のある情報切替に使う。",
    "tags": "ピント 手前 奥 フォーカス",
    "youtube": "https://www.youtube.com/results?search_query=rack+focus+filmmaking+tutorial",
    "preview": "focus",
    "animate": true
  },
  {
    "id": "E01",
    "name": "B-roll差し込み",
    "category": "カット・つなぎ",
    "method": "撮影＋AE",
    "desc": "インタビュー中に仕事風景や手元を差し込む",
    "use": "会社紹介 / 社員インタビュー",
    "tech": "素材選定 / カット編集",
    "note": "話している内容と一致する画を選ぶ。",
    "tags": "B-roll インタビュー 差し込み",
    "youtube": "https://www.youtube.com/results?search_query=B-roll+corporate+interview+editing",
    "preview": "broll",
    "animate": false
  },
  {
    "id": "E02",
    "name": "Jカット / Lカット",
    "category": "カット・つなぎ",
    "method": "AE",
    "desc": "音を先行・継続させて会話を自然につなぐ",
    "use": "インタビュー / 導入事例",
    "tech": "Audio Edit / Timeline",
    "note": "映像だけでなく音のつながりでテンポを作る。",
    "tags": "Jカット Lカット 音声",
    "youtube": "https://www.youtube.com/watch?v=Nqoev3JPXig",
    "preview": "jlcut",
    "animate": false
  },
  {
    "id": "E03",
    "name": "ワイド→ミディアム→クローズ",
    "category": "カット・つなぎ",
    "method": "撮影＋AE",
    "desc": "同じ動作を画角違いでつないで見やすくする",
    "use": "作業紹介 / 製品紹介",
    "tech": "Shot Size Design",
    "note": "同じ動作を複数サイズで撮っておく。",
    "tags": "ワイド ミディアム クローズ",
    "youtube": "https://www.youtube.com/results?search_query=wide+medium+close+shot+sequence+filmmaking",
    "preview": "shotseq",
    "animate": false
  },
  {
    "id": "V01",
    "name": "スピードランプ",
    "category": "映像演出",
    "method": "AE",
    "desc": "移動シーンを加速・減速してテンポを作る",
    "use": "施設導線 / 移動 / ダイジェスト",
    "tech": "Time Remap / Graph Editor",
    "note": "ビジネス動画では短く控えめに。",
    "tags": "速度 加速 減速",
    "youtube": "https://www.youtube.com/results?search_query=After+Effects+speed+ramp+tutorial",
    "preview": "speedramp",
    "animate": true
  },
  {
    "id": "V02",
    "name": "パララックス",
    "category": "映像演出",
    "method": "AE",
    "desc": "静止画を前景・背景に分けて奥行きを出す",
    "use": "沿革 / 写真紹介",
    "tech": "3D Layer / Camera",
    "note": "動かしすぎると写真が不自然になる。",
    "tags": "静止画 2.5D 奥行き",
    "youtube": "https://www.youtube.com/results?search_query=After+Effects+parallax+photo+tutorial",
    "preview": "parallax",
    "animate": true
  },
  {
    "id": "U01",
    "name": "PCブラウザ・モック",
    "category": "UI表現",
    "method": "AE",
    "desc": "Webサービス画面を整えて見せる",
    "use": "SaaS / Webサービス",
    "tech": "Pre-compose / Drop Shadow",
    "note": "ブラウザ枠より画面内容を大きく見せる。",
    "tags": "PC ブラウザ SaaS UI",
    "youtube": "https://www.youtube.com/results?search_query=After+Effects+website+UI+mockup+animation",
    "preview": "browser",
    "animate": false
  },
  {
    "id": "U02",
    "name": "カーソル・クリック",
    "category": "UI表現",
    "method": "AE",
    "desc": "操作箇所をカーソルと反応で示す",
    "use": "マニュアル / 機能説明",
    "tech": "Position / Scale / Motion Path",
    "note": "クリック対象側にも小さく反応を付ける。",
    "tags": "カーソル クリック ボタン",
    "youtube": "https://www.youtube.com/results?search_query=After+Effects+cursor+click+animation+tutorial",
    "preview": "cursor",
    "animate": true
  },
  {
    "id": "T01",
    "name": "フェードイン / フェードアウト",
    "category": "トランジション",
    "method": "AE",
    "desc": "暗転・明転で静かに始める／終える",
    "use": "OP / ED / 余韻",
    "tech": "Opacity / Dip to Black",
    "note": "企業動画で使いやすい定番。長すぎるとテンポが落ちる。",
    "tags": "フェード 暗転 明転",
    "youtube": "https://www.youtube.com/results?search_query=After+Effects+fade+transition+tutorial",
    "preview": "fade",
    "animate": true
  },
  {
    "id": "T02",
    "name": "クロスディゾルブ",
    "category": "トランジション",
    "method": "AE",
    "desc": "2カットを重ねながら自然に移行する",
    "use": "時間経過 / 穏やかな場面転換",
    "tech": "Opacity Crossfade",
    "note": "意味の近いカット同士をつなぐと自然。",
    "tags": "ディゾルブ クロスフェード",
    "youtube": "https://www.youtube.com/results?search_query=After+Effects+cross+dissolve+transition",
    "preview": "dissolve",
    "animate": true
  },
  {
    "id": "T03",
    "name": "ワイプ",
    "category": "トランジション",
    "method": "AE",
    "desc": "次の画面が前の画面を拭うように切り替わる",
    "use": "章切替 / 図解 / UI",
    "tech": "Linear Wipe / Mask / Track Matte",
    "note": "ビジネス動画では直線ワイプが使いやすい。",
    "tags": "ワイプ 左右 上下",
    "youtube": "https://www.youtube.com/results?search_query=After+Effects+wipe+transition+tutorial",
    "preview": "wipe",
    "animate": true
  },
  {
    "id": "T04",
    "name": "スライド / プッシュ",
    "category": "トランジション",
    "method": "AE",
    "desc": "画面全体を横移動させて次の情報へ進める",
    "use": "章切替 / UI / ステップ",
    "tech": "Position / Motion Blur",
    "note": "方向を統一すると資料動画と相性が良い。",
    "tags": "スライド プッシュ 横移動",
    "youtube": "https://www.youtube.com/results?search_query=After+Effects+push+slide+transition+tutorial",
    "preview": "pushtrans",
    "animate": true
  }
];
window.CATEGORIES = ["すべて", "モーション", "図解・データ", "構図・レイアウト", "カメラワーク", "カット・つなぎ", "映像演出", "UI表現", "トランジション"];
window.METHODS = ["すべて", "AE", "撮影", "撮影＋AE"];
